### PR TITLE
fix imports for RN>= 26

### PR DESCRIPTION
**Pull request by vonovak**

### CODE REVIEW

**Comment by vonovak** [comment]
ping @mikemonteith can you please merge this? thanks!

**Comment by mikemonteith** [comment]
Sorry @vonovak I was on holiday when you sent this and I totally forgot.
Thank you for the PR!

**Comment by mikemonteith** [comment]
@vonovak This is a breaking change for people using an older version of React right?

**Comment by vonovak** [comment]
Yes, that is correct. I think most people have upgraded to 0.26 by now
though.

**Pull request merged**
